# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_auto_20201127_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1ID', models.IntegerField()),
                ('friend2ID', models.IntegerField()),
            ],
        ),
    ]
