# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='school',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='theapp.School'),
            preserve_default=False,
        ),
    ]
